import manifest from './brandLogosManifest.json';

/**
 * Discovered brand logo image paths from public/images/brand-logo/
 * Automatically generated by scripts/generate-brand-logo-manifest.js
 */
export const brandLogos: string[] = Array.isArray(manifest) ? (manifest as string[]) : [];

export default brandLogos;
